feat(#20): 공통 로그인 페이지 구현
DKU-SWExpert/SOLID-KPI-FE pull request #25
Opened 2024-12-19 16:11 UTC by digitpic

## 📌 Related Issue

> [!NOTE]
> 관련된 이슈 번호를 적어주세요.

- Close #20

## 🚀 Description

> [!NOTE]
> 작업한 내용을 간략히 적어주세요.

```text
공통 로그인 페이지 구현
```

## 📸 Screenshot
> [!NOTE]
> 변경 사항을 보여주는 스크린샷(또는 GIF)을 첨부해 주세요.
![image](https://github.com/user-attachments/assets/56711edd-cba9-4650-bad1-21e57f09735e)

## 📢 Notes

> [!NOTE]
> 추가적인 설명이나 참고 사항을 작성해 주세요.

```text

```

2024-12-19 17:10 UTC, HoyeongJeon requested changes

2024-12-19 17:14 UTC, HoyeongJeon commented
고생하셨습니다!

2024-12-19 17:21 UTC, JHZLO approved these changes
제가 봤을 떄는 군더더기 없는 깔끔한 구현인 것 같습니다.. 고생하셨습니다!

2024-12-19 23:56 UTC, digitpic commented on src/pages/Login/index.tsx
>  const Login: React.FC = () => {
오! 몰랐던 내용인데 덕분에 배워갑니다 감사합니다

2024-12-20 02:13 UTC, digitpic commented on src/pages/Login/index.tsx
> +    const [username, setUsername] = React.useState<string>("")
우선 [제공해주신 로그인 페이지](https://jobda.kr/solidkpi/employee/login.html) 참고해서 작성했습니다! 나중에 확실해지면 그때 변경해보는 건 어떨까요?

2024-12-20 02:17 UTC, digitpic commented on src/pages/Login/index.tsx
> +    const handleSubmit = (e: FormEvent) => {
반영했습니다!

2024-12-20 02:34 UTC, HoyeongJeon approved these changes
LGTM!

2024-12-20 02:36 UTC, merged