feat(#21): SW 역량 테스트 신청 페이지 UI 구현
DKU-SWExpert/SOLID-KPI-FE pull request #29
Opened 2024-12-20 15:02 UTC by digitpic

## 📌 Related Issue

> [!NOTE]
> 관련된 이슈 번호를 적어주세요.

- Close #21

## 🚀 Description

> [!NOTE]
> 작업한 내용을 간략히 적어주세요.

```text
SW 역량 테스트 신청 페이지 UI 구현
```

## 📸 Screenshot
> [!NOTE]
> 변경 사항을 보여주는 스크린샷(또는 GIF)을 첨부해 주세요.
![image](https://github.com/user-attachments/assets/ed677546-4279-4f75-8870-ce68fc6b3a84)

## 📢 Notes

> [!NOTE]
> 추가적인 설명이나 참고 사항을 작성해 주세요.

```text
UI 는 구현했는데, 아직 내부 데이터 처리는 구현되지 않았습니다
```

2024-12-20 17:03 UTC, HoyeongJeon requested changes

2024-12-20 17:03 UTC, HoyeongJeon commented on src/components/TestCategory/index.tsx
> +                <option value="topcit">TOPCIT</option>
```typescript
const tests = {
  topcit : TOPCIT,
  pccp : PCCP,
  pce : PCCE
}

       {Object.entries(tests).map(([key, value]) => (
              <option key={key} value={key}>
                {value}
              </option>
            ))}
```
이런식으로도 작성하면 좋을거같습니다! 
추후 테스트가 더 추가되는 경우에도 수정이 편할거같아요.

2024-12-20 17:04 UTC, HoyeongJeon commented
고생하셨습니다.

2024-12-20 17:05 UTC, HoyeongJeon commented on src/components/TestCategory/index.tsx
> +                <option value="topcit">TOPCIT</option>
추가로 컴포넌트들을 전부 분리했는데, 이런 경우엔 save 시 별개의 컴포넌트에서 데이터를 어떻게 한번에 서버로 보내나요??

2024-12-21 05:04 UTC, digitpic commented on src/components/TestCategory/index.tsx
> +                <option value="topcit">TOPCIT</option>
말씀해 주신 내용 반영한 수정 커밋 남겼고,
데이터 처리 로직 담은 추가 커밋도 남겼습니다!

2024-12-21 15:56 UTC, JHZLO approved these changes
고생하셨습니다!

2024-12-22 14:29 UTC, closed without merging