feat(#61):DKUStarTrack 페이지 생성
DKU-SWExpert/SOLID-KPI-FE pull request #62
Opened 2024-12-26 08:41 UTC by dndqls

## 📌 Related Issue

> [!NOTE]
> 관련된 이슈 번호를 적어주세요.

- Close #dku-startrack 페이지 생성 #61

## 🚀 Description

> [!NOTE]
> 작업한 내용을 간략히 적어주세요.

```text
DKUStarTrack 페이지 생성
```

## 📸 Screenshot
> [!NOTE]
> 변경 사항을 보여주는 스크린샷(또는 GIF)을 첨부해 주세요.
<img width="1366" alt="스크린샷 2024-12-26 오후 4 35 24(2)" src="https://github.com/user-attachments/assets/1c3de765-b4d7-4138-acff-57d7ece137cb" />
<img width="1357" alt="스크린샷 2024-12-26 오후 5 40 57" src="https://github.com/user-attachments/assets/8dbe5132-a172-4a78-86d4-6160d166823a" />

## 📢 Notes

> [!NOTE]
> 추가적인 설명이나 참고 사항을 작성해 주세요.

```text

```

2024-12-26 09:57 UTC, HoyeongJeon requested changes

2024-12-26 09:57 UTC, HoyeongJeon commented on src/pages/Student/scholarship/DKUStarTrack/index.tsx
> +                            <CFormLabel className="text-white">학번</CFormLabel>
화면명세서를 보면 학번, 이름, 학과는 이미 정해져있습니다.
학생이 초기 입력을 하던지, 가입을 한 정보를 사용하는 것인데요, 현재 코드에선 입력을 받도록 되어있어요. 
이 부분을 고치면 좋을거 같습니다. 
방법은 많은데, 현재 백엔드랑 연동이 안되어서 제가 stores 폴더에 user.ts에 정보를 넣어놨습니다. 
이런 것을 "상태관리"라고 하는데요, 
혹시 지금 처음 알게되셨다면 "상태관리"에 대해 찾아보시면 알게 될거에요.
추가로 상태관리를 위해 제가 사용한 라이브러리는 "zustand"이니 해당 라이브러리 사용법도 찾아보시면 좋을거에요.
관련 코드는 src/pages/Student/Internship/Application.tsx 코드를 보아도 있으니 참고해주세요.

2024-12-26 09:57 UTC, HoyeongJeon commented on src/pages/Student/scholarship/DKUStarTrack/index.tsx
> +                            <CFormLabel className="text-white">학번</CFormLabel>
화면명세서는 고덕한 이사님이 만드신 사이트입니다.

2024-12-26 09:57 UTC, HoyeongJeon commented on src/pages/Student/scholarship/DKUStarTrack/index.tsx
> +                                placeholder="홍길동"
위 리뷰와 동일합니다.

2024-12-26 09:57 UTC, HoyeongJeon commented on src/pages/Student/scholarship/DKUStarTrack/index.tsx
> +                                placeholder="소프트웨어"
위 리뷰와 동일합니다.

2024-12-28 15:12 UTC, JHZLO approved these changes
issue, pr 컨벤션 잘 지켜주셨네요!
commit 컨벤션에도 조금 더 신경 써주시면 더 좋을 것 같습니다!
고생하셨습니다.

2024-12-29 02:11 UTC, HoyeongJeon approved these changes

2024-12-29 06:48 UTC, merged