feat(#63): [SW 유망주] 페이지 생성
DKU-SWExpert/SOLID-KPI-FE pull request #72
Opened 2024-12-29 13:34 UTC by jun562

## 📌 Related Issue

> [!NOTE]
> 관련된 이슈 번호를 적어주세요.

- Close #63 

## 🚀 Description

> [!NOTE]
> 작업한 내용을 간략히 적어주세요.

```
SW 유망주 페이지 생성
```

## 📸 Screenshot
> [!NOTE]
> 변경 사항을 보여주는 스크린샷(또는 GIF)을 첨부해 주세요.
<img width="1120" alt="유망주1" src="https://github.com/user-attachments/assets/e9581611-6af6-41d1-ade8-89fd355183dd" />
<img width="1115" alt="유망주2" src="https://github.com/user-attachments/assets/ea50b018-e64f-4722-b65a-96505ea55b5a" />

## 📢 Notes

> [!NOTE]
> 추가적인 설명이나 참고 사항을 작성해 주세요.

```text

```

2024-12-30 00:48 UTC, HoyeongJeon requested changes

2024-12-30 00:48 UTC, HoyeongJeon commented on src/pages/Student/SwRisingStar/index.tsx
> +  function addHyphen(obj: HTMLInputElement): void {
- 변수명은 어떤 의미인가요?
- 위에선 const로 함수를 작성했고, 여기선 function으로 했는데 다른 방식으로 함수를 만든 이유가 있나요?

2024-12-30 00:48 UTC, HoyeongJeon commented on src/pages/Student/SwRisingStar/index.tsx
> +    if (!formData.selectedPeriod) {
formData에 대한 검증 로직이 handleSave 함수 안에 있습니다.
검증 로직을 분리해도 좋을거같아요.

```typescript
const validateFormData = () => {
   검증로직...
}

const handleSave = () => {
   validateFormData();
   ...
}

이런 느낌으로요.
그냥 예시로 작성한 코드니까 편하게 구현하시면 됩니다.

```

2024-12-30 00:48 UTC, HoyeongJeon commented on src/pages/Student/SwRisingStar/index.tsx
> +  function addHyphen(obj: HTMLInputElement): void {
파라미터 변수의 이름이 obj인데 더 명확한 변수 이름을 사용하는게 좋을거같습니다.

2024-12-30 00:48 UTC, HoyeongJeon commented on src/pages/Student/SwRisingStar/index.tsx
> +    if (len < 4) {
4보다 길이가 짧을 때 얼리리턴을 하면 불필요한 중첩문을 없앨 수 있을거같습니다.
```typescript
if (len < 4) {
    phoneInput.value = num;
    return;
  }
```

이런 느낌이요.

2024-12-30 00:48 UTC, HoyeongJeon commented on src/pages/Student/SwRisingStar/index.tsx
> +    if (len < 4) {
추가로 로직이 생각나진 않는데, if 문을 줄일 수 있으면 좋을거같습니다.

2024-12-30 00:51 UTC, HoyeongJeon commented on src/pages/Student/scholarship/SwRisingStar/index.tsx
> +        <CCardHeader className="text-white">신청서(기본정보)</CCardHeader>
https://jobda.kr/solidkpi/student/dku_startrack_add.html
화면명세서를 보면 학번, 이름, 학과는 이미 정해져있습니다.
학생이 초기 입력을 하던지, 가입을 한 정보를 사용하는 것인데요, 현재 코드에선 입력을 받도록 되어있어요.
이 부분을 고치면 좋을거 같습니다.
방법은 많은데, 현재 백엔드랑 연동이 안되어서 제가 stores 폴더에 user.ts에 정보를 넣어놨습니다.
이런 것을 "상태관리"라고 하는데요,
혹시 지금 처음 알게되셨다면 "상태관리"에 대해 찾아보시면 알게 될거에요.
추가로 상태관리를 위해 제가 사용한 라이브러리는 "zustand"이니 해당 라이브러리 사용법도 찾아보시면 좋을거에요.
관련 코드는 src/pages/Student/Internship/Application.tsx 코드를 보아도 있으니 참고해주세요.

2024-12-30 16:36 UTC, jun562 commented on src/pages/Student/SwRisingStar/index.tsx
> +    if (!formData.selectedPeriod) {
넵! 수정완료했습니다.

2024-12-30 16:36 UTC, jun562 commented on src/pages/Student/scholarship/SwRisingStar/index.tsx
> +        <CCardHeader className="text-white">신청서(기본정보)</CCardHeader>
수정 완료했습니다!

2024-12-31 05:36 UTC, HoyeongJeon approved these changes
LGTM~!

2024-12-31 06:24 UTC, merged